name: Rust
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apt dependencies
        run: |
          sudo apt update && sudo apt install -y libusb-1.0-0-dev
      - name: Get & Make Phidgets22
        run: |
          wget https://www.phidgets.com/downloads/phidget22/libraries/linux/libphidget22.tar.gz
          tar zxvf libphidget22.tar.gz
          rm libphidget22.tar.gz
          cd libphidget22*
          ./configure --prefix=/usr && make -j$(nproc) && sudo make install
          cd ..
      - name: Build Release
        run: cargo build --release --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: rustphidgets
          path: target/release/rustphidgets

env:
  CARGO_TERM_COLOR: always
